<h1>Лабораторна робота №1<h1>

<h2>2. ЗАВДАННЯ НА ЛАБОРАТОРНУ РОБОТУ ТА МЕТОДИЧНІ РЕКОМЕНДАЦІЇ ДО ЙОГО ВИКОНАННЯ</h2>
<h3>Завдання 2.1. Попередня обробка даних</h3>
<p>Створимо новий Jupiter Notebook та імпортуймо такі пакети.</p>

In [135]:
import numpy as np
import math
from sklearn import preprocessing
from sklearn import linear_model
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

<p>Визначимо деяку вибірку даних.</p>

In [2]:
input_data = np.array([[5.1, -2.9, 3.3],
                        [-1.2, 7.8, -6.1],
                        [3.9, 0.4, 2.1],
                        [7.3, -9.9, -4.5]])

<p>Розглянемо декілька різних методів попередньої обробки даних.</p>

<h4>2.1.1. Бінаризація</h4>
<p>Додамо наступні рядки до того ж Jupiter Notebook.</p>

In [ ]:
# Бінаризація даних
data_binarized = preprocessing.Binarizer(threshold=2.1).transform(input_data)
print("\n Binarized data:\n", data_binarized)


 Binarized data:
 [[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


<p>Як бачимо, всі значення понад 1 примусово встановлюються рівними 1. Інші значення стають рівними 0.</p>

<h4>2.1.2 Виключення середнього</h4>
<p>Додамо наступні рядки до нашого Jupiter Notebook, який використовувався в попередньому завданні 2.1.1.</p>

In [73]:
# Виведення середнього значення та стандартного відхилення

print("\nBEFORE: ")
print("Mean = ", input_data.mean(axis=0))
print("Std deviation =", input_data.std(axis=0))


BEFORE: 
Mean =  -1.5250000000000001
Std deviation = [0.71195154 2.82875856 4.79446295]


<p>Ці рядки коду відображають середнє значення і середньоквадратичне відхилення для вхідних даних.</p>
<p>Тепер виключимо середнє значення.</p>

In [77]:
# Виключення середнього значення

data_scaled = preprocessing.scale(input_data)
print("\nAFTER: ")
print("Mean =", data_scaled.mean(axis=0))
print("Std deviation =", data_scaled.std(axis=0))


AFTER: 
Mean = [-4.44089210e-16 -5.55111512e-17  6.93889390e-17]
Std deviation = [1. 1. 1.]


<p>Неважко помітити, що середнє значення практично рівне нулю, а стандартне відхилення - одиниці.</p>

<h4>2.1.3. Масштабування</h4>
<p>Додамо до того ж Jupiter Notebook наступні рядки.</p>

In [8]:
#Масштабування MinMax

data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print("\nMinMax scaled data:\n", data_scaled_minmax)


MinMax scaled data:
 [[0.74117647 0.39548023 1.        ]
 [0.         1.         0.        ]
 [0.6        0.5819209  0.87234043]
 [1.         0.         0.17021277]]


<p>Кожен рядок відмасштабований таким чином, щоб максимальним значенням була б одиниця, а всі решта значень визначалися відносно неї.</p>

<h4>2.1.4. Нормалізація</h4>
<p>Додамо наступні рядки у наш файл.</p>

In [9]:
#Нормалізація даних

data_normalized_l1 = preprocessing.normalize(input_data,norm='l1')
data_normalized_l2 = preprocessing.normalize(input_data,norm='l2')
print("\nL1 normalized data:\n", data_normalized_l1)
print("\nL2 normalized data:\n", data_normalized_l2)


L1 normalized data:
 [[ 0.45132743 -0.25663717  0.2920354 ]
 [-0.0794702   0.51655629 -0.40397351]
 [ 0.609375    0.0625      0.328125  ]
 [ 0.33640553 -0.4562212  -0.20737327]]

L2 normalized data:
 [[ 0.75765788 -0.43082507  0.49024922]
 [-0.12030718  0.78199664 -0.61156148]
 [ 0.87690281  0.08993875  0.47217844]
 [ 0.55734935 -0.75585734 -0.34357152]]


<p>Виконаємо обернену дію та перевіримо алгоритми, що використовуються для нормалізованих даних.</p>

In [56]:
#Перевірка L1-нормалізації
print("L1 normanlization test:\n")
for row in data_normalized_l1:
    print(math.fsum(abs(row)))

#Перевірка L2-нормалізації
print("\nL2 normalization test:\n")
for row in data_normalized_l2:
    print(math.fsum(pow(row,2)))

L1 normanlization test:

0.9999999999999998
1.0
1.0
1.0

L2 normalization test:

0.9999999999999998
1.0
1.0
1.0


<p>Таким чином ми підвердили дію алгоритмів. В методичному варіанті вказано, що L2-нормалізація менш чутлива до викидів, тому бажано використовувати саме цей алгоритм.</p>

<h4>2.1.5. Кодування міток</h4>

<p>Визначимо мітки.</p>

In [57]:
# Надання позначок вхідних даних

input_labels = ['red', 'black', 'green', 'black', 'yellow', 'white']

<p>Створимо обʼєкт кодування міток та навчимо його.</p>

In [58]:
# Створення кодувальника та встановлення відповідності між мітками та числами

encoder = preprocessing.LabelEncoder()
encoder.fit(input_labels)

LabelEncoder()

<p>Виведемо відображення слів на числа.</p>

In [63]:
# Виведення відображення

print("\nLabel mapping:")
for i, item in enumerate(encoder.classes_):
    print(item, '-->', i)


Label mapping:
black --> 0
green --> 1
red --> 2
white --> 3
yellow --> 4


<p>Перетворимо набір випадково впорядкованих міток, щоб перевірити роботу кодувальника.</p>

In [64]:
# Перетворення міток за допомогою кодувальника

test_labels = ['green', 'red', 'black']
encoded_values = encoder.transform(test_labels)
print("\nLabels =", test_labels)
print("Encoded values =", list(encoded_values))


Labels = ['green', 'red', 'black']
Encoded values = [1, 2, 0]


<p>Декодуємо випадковий набір чисел.</p>

In [65]:
# Декодування набору чисел за допомогою декодера
encoded_values = [3, 0, 4, 1]
decoded_list = encoder.inverse_transform(encoded_values)
print("\nEncoded values =", encoded_values)
print("Decoded labels =", list(decoded_list))


Encoded values = [3, 0, 4, 1]
Decoded labels = ['white', 'black', 'yellow', 'green']


<p>Таким чином отримали практичні навички з кодування та декодування міток за допомогою пакету preprocessing.</p>

<h3>Завдання 2.2. Попередня обробка нових даних</h3>

<p>Варіант №16</p>
<table>
    <tr>
        <th>№ варіанту</th>
        <th colspan="12">Значення змінної input_data</th>
        <th>Поріг бінаризації</th>
    </tr>
    <tr>
        <td>16.</td>
        <td>-3.3</td>
        <td>-1.6</td>
        <td>6.1</td>
        <td>-2.4</td>
        <td>-1.2</td>
        <td>4.3</td>
        <td>-3.2</td>
        <td>5.5</td>
        <td>-6.1</td>
        <td>-4.4</td>
        <td>1.4</td>
        <td>-1.2</td>
        <td>2.1</td>
    </tr>
</table>

Бінарізації, Виключення середнього, Масштабування, Нормалізації.

<p>Вхідні дані:</p>

In [67]:
input_data = np.array([[-3.3, -1.6, 6.1],
                    [-2.4, -1.2, 4.3],
                    [-3.2, 5.5, -6.1],
                    [-4.4, 1.4, -1.2]])

<p>Бінаризація даних</p>

In [68]:
data_binarized = preprocessing.Binarizer(threshold=2.1).transform(input_data)
print("Binarized data: \n", data_binarized)

Binarized data: 
 [[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 0.]]


<p>Виключення середнього</p>

In [69]:
print("BEFORE:")
print("Mean = ", input_data.mean(axis=0))
print("Std deviation =", input_data.std(axis=0))

BEFORE:
Mean =  [-3.325  1.025  0.775]
Std deviation = [0.71195154 2.82875856 4.79446295]


<p>Тепер виключимо середнє значення</p>

In [78]:
data_scaled = preprocessing.scale(input_data)
print("AFTER:")
print("Mean =", (data_scaled.mean(axis=0)))
print("Std deviatuion =", data_scaled.std(axis=0))

AFTER:
Mean = [-4.44089210e-16 -5.55111512e-17  6.93889390e-17]
Std deviatuion = [1. 1. 1.]


<p>Неважко помітити, що середнє значення практично рівне 0, а стандартне відхилення - 1.</p>

<p>Масштабування</p>

In [79]:
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print("Min max scaled data:\n", data_scaled_minmax)

Min max scaled data:
 [[0.55       0.         1.        ]
 [1.         0.05633803 0.85245902]
 [0.6        1.         0.        ]
 [0.         0.42253521 0.40163934]]


<p>Кожен рядок відформатовано таким чином, щоб максимальним значенням була б одиниця, а всі решта значень визначалися відносно неї.</p>

<p>Нормалізація</p>

In [81]:
data_normalized_l1 = preprocessing.normalize(input_data,norm='l1')
data_normalized_l2 = preprocessing.normalize(input_data,norm='l2')
print("L1 normalized data:\n", data_normalized_l1)
print("\nL2 normalized data:\n", data_normalized_l2)

L1 normalized data:
 [[-0.3        -0.14545455  0.55454545]
 [-0.30379747 -0.15189873  0.5443038 ]
 [-0.21621622  0.37162162 -0.41216216]
 [-0.62857143  0.2        -0.17142857]]

L2 normalized data:
 [[-0.46364048 -0.22479538  0.8570324 ]
 [-0.47351004 -0.23675502  0.84837215]
 [-0.36302745  0.62395344 -0.69202108]
 [-0.92228798  0.29345527 -0.25153308]]


<h3>Завдання 2.3. Класифікація логістичною регресією або логістичний класифікатор</h3>

<p>Визначимо зразок вхідних даних за допомогою двовимірних векторів і відповідних міток.</p>

In [118]:
# Визначення зразка вхідних даних
X = np.array([[3.1, 7.2], [4, 6.7], [2.9, 8], [5.1, 4.5],
            [6, 5], [5.6, 5], [3.3, 0.4], 
            [3.9, 0.9], [2.8, 1],
            [0.5, 3.4], [1, 4], [0.6, 4.9]])
y = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3])

<p>Натренуємо класифікатор, використовуючи ці позначені дані. Створимо обʼєкт логістичного класифікатора.</p>

In [119]:
# Створення логістичного класифікатора

classifier = linear_model.LogisticRegression(solver='liblinear',C=1)

<p>Навчимо класифікатор, використовуючи певні дані.</p>

In [122]:
# Тренування класифікатора

classifier.fit(X, y)

LogisticRegression(C=1, solver='liblinear')

<p>Візуалізувати результати роботи не вдалося, через застарілу бібліотеку, що вказана в методичних матеріалах.</p>

<h3>Завдання 2.4. Класифікація наївним байєсовським класифікатором</h3>

<p>Як джерело даних буде використано файл data_multivar_nb.txt, кожен рядок якого містить значення розділені комою.</p>

In [98]:
# Вхідний файл, який містить дані
input_file = 'data_multivar_nb.txt'

<p>Завантажимо дані із цього файлу.</p>

In [99]:
# Завантаження даних із вхідного файлу
data = np.loadtxt(input_file, delimiter=',')
X, y = data[:, :-1], data[:, -1]

<p>Створимо екземпляр наївного байєсовського класифікатора. У даному випадку ми будемо використовувати гаусівський наївний байєсівський класифікатор, в якому передбачається, що значення, які асоціюються з кожним класом, дотримуються закону розподілу Гауса.</p>

In [100]:
# Створення наївного байєсовського класифікатора
classifier = GaussianNB()

<p>Навчимо класифікатор, використовуючи тренувальні дані.</p>

In [113]:
# Тренування класифікатора
classifier.fit(X, y)

GaussianNB()

<p>Запустимо класифікатор на тренувальних даних та спрогнозуємо результати.</p>

In [102]:
# Прогнозування значень для тренувальних даних
y_pred = classifier.predict(X)

<p>Обчислимо якість (accuracy)1 класифікатора, порівнявши передбачені значення з істинними мітками.</p>

In [103]:
# Обчислення якості класифікатора
accuracy = 100.0 * (y == y_pred).sum() / X.shape[0]
print("Accuracy of Naive Bayes classifier =", round(accuracy,
2), "%")

Accuracy of Naive Bayes classifier = 99.75 %


<p>Розіб'ємо дані на навчальний та тестовий набори. Відповідно до значення параметра test_size, зазначеного в рядку коду нижче, ми віднесемо 80% даних до тренування, а 20% - до тестування. Потім ми виконаємо тренування наївним байєсовським класифікатором на цих даних.</p>

In [139]:
# Розбивка даних на навчальний та тестовий набори

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)
classifier_new = GaussianNB()
classifier_new.fit(X_train, y_train)
y_test_pred = classifier_new.predict(X_test)

<p>Обчислимо якість класифікатора.</p>

In [131]:
# Обчислення якості класифікатора
accuracy = 100.0 * (y_test == y_test_pred).sum()/X_test.shape[0]
print("Accuracy of the new classifier =", round(accuracy, 2),"%")

Accuracy of the new classifier = 33.33 %


<p>Скористаємося вбудованими функціями для обчислення якості (accuracy), точності (precision) 2 та повноти (recall) 3 класифікатора на підставі потрійний перехрестної перевірки.</p>

In [152]:
num_folds = 3
accuracy_values = cross_val_score(classifier,X, y, scoring='accuracy', cv=num_folds)
print("Accuracy: " + str(round(100 * accuracy_values.mean(), 2))+ "%")
precision_values = cross_val_score(classifier,X, y, scoring='precision_weighted', cv=num_folds)
print("Precision: " + str(round(100 * precision_values.mean(),2)) + "%")
recall_values = cross_val_score(classifier, X, y, scoring='recall_weighted', cv=num_folds)
print("Recall: " + str(round(100 * recall_values.mean(), 2)) + "%")
f1_values = cross_val_score(classifier,X, y, scoring='f1_weighted', cv=num_folds)
print("F1: " + str(round(100 * f1_values.mean(), 2)) + "%")

Accuracy: 91.67%
Precision: 87.5%
Recall: 91.67%
F1: 88.89%


/opt/homebrew/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.


<h3>Завдання 2.5. Вивчити метрики якості класифікації</h3>