<h1>Лабораторна робота №1<h1>

<h2>2. ЗАВДАННЯ НА ЛАБОРАТОРНУ РОБОТУ ТА МЕТОДИЧНІ РЕКОМЕНДАЦІЇ ДО ЙОГО ВИКОНАННЯ</h2>
<h3>Завдання 2.1. Попередня обробка даних</h3>
<p>Створимо новий Jupiter Notebook та імпортуймо такі пакети.</p>

In [14]:
import numpy as np
import math
from sklearn import preprocessing

<p>Визначимо деяку вибірку даних.</p>

In [2]:
input_data = np.array([[5.1, -2.9, 3.3],
                        [-1.2, 7.8, -6.1],
                        [3.9, 0.4, 2.1],
                        [7.3, -9.9, -4.5]])

<p>Розглянемо декілька різних методів попередньої обробки даних.</p>

<h4>2.1.1. Бінаризація</h4>
<p>Додамо наступні рядки до того ж Jupiter Notebook.</p>

In [ ]:
# Бінаризація даних
data_binarized = preprocessing.Binarizer(threshold=2.1).transform(input_data)
print("\n Binarized data:\n", data_binarized)


 Binarized data:
 [[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


<p>Як бачимо, всі значення понад 1 примусово встановлюються рівними 1. Інші значення стають рівними 0.</p>

<h4>2.1.2 Виключення середнього</h4>
<p>Додамо наступні рядки до нашого Jupiter Notebook, який використовувався в попередньому завданні 2.1.1.</p>

In [5]:
# Виведення середнього значення та стандартного відхилення

print("\nBEFORE: ")
print("Mean = ", input_data.mean(axis=0))
print("Std deviation =", input_data.std(axis=0))


BEFORE: 
Mean =  [ 3.775 -1.15  -1.3  ]
Std deviation = [3.12039661 6.36651396 4.0620192 ]


<p>Ці рядки коду відображають середнє значення і середньоквадратичне відхилення для вхідних даних.</p>
<p>Тепер виключимо середнє значення.</p>

In [6]:
# Виключення середнього значення

data_scaled = preprocessing.scale(input_data)
print("\nAFTER: ")
print("Mean =", data_scaled.mean(axis=0))
print("Std deviation =", data_scaled.std(axis=0))


AFTER: 
Mean = [1.11022302e-16 0.00000000e+00 2.77555756e-17]
Std deviation = [1. 1. 1.]


<p>Неважко помітити, що середнє значення практично рівне нулю, а стандартне відхилення - одиниці.</p>

<h4>2.1.3. Масштабування</h4>
<p>Додамо до того ж Jupiter Notebook наступні рядки.</p>

In [8]:
#Масштабування MinMax

data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print("\nMinMax scaled data:\n", data_scaled_minmax)


MinMax scaled data:
 [[0.74117647 0.39548023 1.        ]
 [0.         1.         0.        ]
 [0.6        0.5819209  0.87234043]
 [1.         0.         0.17021277]]


<p>Кожен рядок відмасштабований таким чином, щоб максимальним значенням була б одиниця, а всі решта значень визначалися відносно неї.</p>

<h4>2.1.4. Нормалізація</h4>
<p>Додамо наступні рядки у наш файл.</p>

In [9]:
#Нормалізація даних

data_normalized_l1 = preprocessing.normalize(input_data,norm='l1')
data_normalized_l2 = preprocessing.normalize(input_data,norm='l2')
print("\nL1 normalized data:\n", data_normalized_l1)
print("\nL2 normalized data:\n", data_normalized_l2)


L1 normalized data:
 [[ 0.45132743 -0.25663717  0.2920354 ]
 [-0.0794702   0.51655629 -0.40397351]
 [ 0.609375    0.0625      0.328125  ]
 [ 0.33640553 -0.4562212  -0.20737327]]

L2 normalized data:
 [[ 0.75765788 -0.43082507  0.49024922]
 [-0.12030718  0.78199664 -0.61156148]
 [ 0.87690281  0.08993875  0.47217844]
 [ 0.55734935 -0.75585734 -0.34357152]]


<p>Виконаємо обернену дію та перевіримо алгоритми, що використовуються для нормалізованих даних.</p>

In [56]:
#Перевірка L1-нормалізації
print("L1 normanlization test:\n")
for row in data_normalized_l1:
    print(math.fsum(abs(row)))

#Перевірка L2-нормалізації
print("\nL2 normalization test:\n")
for row in data_normalized_l2:
    print(math.fsum(pow(row,2)))

L1 normanlization test:

0.9999999999999998
1.0
1.0
1.0

L2 normalization test:

0.9999999999999998
1.0
1.0
1.0


<p>Таким чином ми підвердили дію алгоритмів. Не дивлячись на різні методи ми отримали однаковий результат, проте в методичному варіанті вказано, що L2-нормалізація менш чутлива до викидів, тому бажано використовувати саме цей алгоритм.</p>

<h4>2.1.5. Кодування міток</h4>

<p>Визначимо мітки</p>